### ISSUE TITLE
Editing profile E-mail won't save

### ISSUE THREAD

**Issue by Boyfinn** [trafiklab/trafiklab.se#14]
The subpage for editing user page (/user/UID/edit) won't save changes to the e-mail field.
Tested on:
Firefox 100.0.2
Google Chrome 100.0.4896.60
Microsoft Edge 101.0.1210.53

**Comment by Bertware** [comment]
Hi,

Thanks for reporting this issue. Note that this issue actually is part of another website/platform (developer.trafiklab.se instead of trafiklab.se).
I have tested this using Firefox 100 and successfully changed my e-mail address on a normal account. You have to write your current password in the field above the e-mail address, and leave the two password fields below (for a password change) empty.

We are currently working on a replacement for the developer.trafiklab.se platform, which should resolve these issues in the user experience.

Regards,
Bert

**Comment by Bertware** [comment]
Weird, please contact us at info@trafiklab.se for further assistance.
